import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Iliokahu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='font-corals bg-background text-black'
      >
              <header>test</header>
        {children}
      </body>
    </html>
  );
}
