import type { Metadata } from "next";
import Navbar from './components/navBar';
import "./globals.css";


export const metadata: Metadata = {
  title: "Iliokahu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="fr">
      <body>
          <header>
            <Navbar/>
          </header>
        {children}
      </body>
    </html>
  );
}
